# Generated by Django 3.2 on 2021-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
